$(function(){
  $(".Behind").click(function(e){
    e.preventDefault()
    $(".modal").fadeIn();
  });
  $(".back").click(function(e){
    e.preventDefault()
    $(".modal").fadeOut();
  })
  $(".modal").click(function(e){
    e.preventDefault()
    $(".modal").fadeOut();
  })
});